import type { ImageId } from "./images";

type FigureText = { alt: string; caption?: string };

export const figures: Record<ImageId, FigureText> = {
  "cover-strip": { alt: "Close-up photograph of a physical model: dark steel stairs and a small timber figure." },
  portrait: { alt: "Black and white portrait of Hita Shah." },

  "cg-sitemap": { alt: "Site map of Edinburgh's peripheral neighbourhoods with the Common Ground site marked." },
  "cg-axo": { alt: "Axonometric of Common Ground: rooms arranged around a central courtyard, with green roofs and a greenhouse.", caption: "Layout of rooms and openings" },
  "cg-plan-1": { alt: "Floor plan of Common Ground set within the surrounding street grid, drawn in sage.", caption: "Floor Plan I" },
  "cg-plan-2": { alt: "Second floor plan of Common Ground within its street grid.", caption: "Floor Plan II" },
  "cg-section-hall": { alt: "Long section through the multipurpose hall: timber structure, clerestory glazing and people playing basketball." },
  "cg-detail-ground": { alt: "Detail section of the ground floor build-up above a pad foundation.", caption: "Ground Floor" },
  "cg-detail-sprung": { alt: "Detail section of the sprung sports floor.", caption: "Sprung Flooring" },
  "cg-section-library": { alt: "Detail section through the library and greenhouse, with the seated staircase under a green roof.", caption: "Detail Section" },
  "cg-detail-greenroof": { alt: "Detail section of the green roof edge.", caption: "Green Roof" },
  "cg-detail-cltwall": { alt: "Detail section of the CLT external wall.", caption: "CLT External Wall" },
  "cg-study-1": { alt: "Render of an individual study area beside tall bookshelves.", caption: "Individual Study" },
  "cg-staircase": { alt: "Render of the seated staircase lined with bookshelves.", caption: "Seated Staircase" },
  "cg-study-2": { alt: "Render of a study room with a long table and a wall-mounted screen.", caption: "Individual Study" },
  "cg-plan-hall": { alt: "Plan of the multipurpose hall with a basketball court.", caption: "Multi-Purpose Hall" },
  "cg-plan-library": { alt: "Plan of the library with a curved seating area and study rooms.", caption: "Library" },
  "cg-hall-1": { alt: "Render of a basketball game in the timber-lined multipurpose hall." },
  "cg-hall-2": { alt: "Render of a concert with coloured stage lights and a crowd." },
  "cg-hall-3": { alt: "Render of tiered seating with people gathered around a round table." },
  "cg-yoga": { alt: "Render of a yoga class in a timber-lined studio." },
  "cg-art": { alt: "Render of an art class with easels around a shared table." },
  "cg-aerial": { alt: "Render of aerial silks practice in a double-height hall." },
  "cg-plan-11a": { alt: "Plan of an activity studio laid out in rows, with an adjoining room." },
  "cg-plan-11b": { alt: "Plan of a long room laid out with tables and seating." },
  "cg-greenhouse": { alt: "Render of people tending plants in the greenhouse." },
  "cg-kitchen": { alt: "Render of the community kitchen with people cooking together." },
  "cg-cooking": { alt: "Render of a cooking session with children gathered around a counter." },

  "fc-photo": { alt: "Halftone photograph of the Faithlie Centre: a Corten steel extension beside a retained stone building." },
  "fc-model-1": { alt: "Physical model of the Faithlie Centre: a perforated Corten facade over the retained stone walls, with scale figures." },
  "fc-model-2": { alt: "Model interior: retained stonework seen past a glass balustrade." },
  "fc-model-3": { alt: "Model detail: the perforated Corten facade above the glazed ground floor." },
  "fc-model-4": { alt: "Model detail: a scale figure inside, framed by the Corten facade." },
  "fc-detail-parapet": { alt: "Axonometric construction detail of the parapet.", caption: "Parapet" },
  "fc-detail-floor": { alt: "Axonometric construction detail of a separating floor.", caption: "Separating Floors" },
  "fc-detail-foundation": { alt: "Axonometric construction detail of the foundations.", caption: "Foundations" },
  "fc-corten": { alt: "Axonometric of a Corten steel facade fragment with vertical fins." },
  "fc-exploded": { alt: "Exploded axonometric of the Faithlie Centre: the building body, glazing, frames and perforated Corten screen pulled apart." },

  "vt-castle": { alt: "Evening render of the Verdant Theatre colonnade, with Edinburgh Castle on the rock behind." },
  "vt-auditorium": { alt: "Render of the auditorium: timber-lined walls and ceiling, rows of seats and a pianist on stage." },
  "vt-map-location": { alt: "Map of Edinburgh with the Verdant Theatre site marked in red." },
  "vt-map-context": { alt: "Analysis map of the Old Town around the site, with landmarks drawn out below." },
  "vt-map-movement": { alt: "Diagram of routes and connections across the site." },
  "vt-map-climate": { alt: "Diagram of wind direction and sun positions across the site.", caption: "Wind Direction" },
  "vt-massing-1": { alt: "Massing diagram of the theatre at a modest scale.", caption: "Modest Scale" },
  "vt-massing-2": { alt: "Massing diagram with arrows showing views out to Edinburgh Castle.", caption: "Views to the Edinburgh Castle" },
  "vt-massing-3": { alt: "Massing diagram with a green ground plane following the slope.", caption: "Adapting to the Topography" },
  "vt-massing-4": { alt: "Massing diagram with orange routes connecting the surrounding streets.", caption: "Connecting the Streets" },
  "vt-massing-5": { alt: "Massing diagram highlighting the public entrances.", caption: "Public Entrances" },
  "vt-sketch": { alt: "Hand-drawn axonometric sketch of the scheme in its Edinburgh context, annotated with the main moves." },
  "vt-form-1": { alt: "Form diagram: a ramp connecting the floors through the volume.", caption: "Connect the Floors" },
  "vt-form-2": { alt: "Form diagram: the public spaces extruded from the volume.", caption: "Extrude the Public Spaces" },
  "vt-form-3": { alt: "Form diagram: the entrances stepped back from the street.", caption: "Step Back the Entrances" },
  "vt-section": { alt: "Section through Verdant Theatre: the auditorium and stage at the centre, rooms on either side and people on the green roof." },
  "vt-exploded": { alt: "Exploded axonometric of Verdant Theatre: green roof, concrete beams, timber panel railing, precast concrete stairs, glazing and retaining wall." },
  "vt-foyer-1": { alt: "Render of the double-height foyer with a bar and people moving between levels." },
  "vt-foyer-2": { alt: "Render of a timber-lined circulation stair." },

  "ea-siteplan": { alt: "Aerial site plan of the former international airport on the Athens coast, with the regeneration masterplan." },
  "ea-courtyard": { alt: "Render of the Elysian Arcadia courtyard: curved timber balconies with trailing plants around a lawn." },
  "ea-plan-site": { alt: "Site plan of the teardrop-shaped blocks with two section lines drawn through them." },
  "ea-plan-a": { alt: "Floor plan of three teardrop-shaped blocks arranged around a central ring." },
  "ea-plan-b": { alt: "Floor plan of the blocks with long rows of green planting beds." },
  "ea-landscape": { alt: "Roof and landscape plan: green roofs and paths linking the blocks." },
  "ea-model-1": { alt: "Physical model: a slender dark frame with a timber stair, balcony and scale figures." },
  "ea-model-2": { alt: "Physical model: a two-storey timber frame with a stair and a glazed upper room." },
  "ea-model-3": { alt: "Model detail: a scale figure behind a glazed screen." },
  "ea-model-4": { alt: "Model detail: timber stairs below a glazed upper level." },
  "ea-sketch": { alt: "Line sketch of a figure resting on the stairs." },
  "ea-elevation-1": { alt: "Elevation of the development with terraced, planted balconies." },
  "ea-elevation-2": { alt: "Long elevation of the development with terraced, planted balconies." },
  "ea-wallsection": { alt: "Wall section: planted balconies on the upper floors and a timber structure on a concrete base." },
  "ea-detail-base": { alt: "Base detail: ventilated timber cladding, CLT wall and concrete slab.", caption: "Base Detail" },
  "ea-detail-floor": { alt: "Intermediate floor detail: CLT floor meeting the CLT wall.", caption: "Intermediate Floor Detail" },
  "ea-balconies": { alt: "Render looking up at curved timber balconies with trailing plants and a colonnade." },
  "ea-facade": { alt: "Render of timber fins and a planted balcony." },
  "ea-bedroom": { alt: "Render of a timber-lined bedroom washed in sunlight." },
  "ea-farm": { alt: "Render of vertical growing walls beside a glazed facade." },
  "ea-concept": { alt: "Concept diagram linking living, growing, education and local, with supervision at the centre." },
  "ea-study-cafe": { alt: "Sketch of a cafe counter.", caption: "Cafe" },
  "ea-study-office": { alt: "Sketch of an office space.", caption: "Office" },
  "ea-study-shared": { alt: "Sketch of a shared space.", caption: "Shared Space" },
  "ea-study-private": { alt: "Sketch of a private room.", caption: "Private" },
  "ea-study-glass": { alt: "Sketch of a glass facade.", caption: "Glass Facade" },
  "ea-study-curved": { alt: "Sketch of a curved facade.", caption: "Curved Facade" },

  "dc-logo": { alt: "Design Concepts logo." },
  "jss-logo": { alt: "JSS Private School logo." },
  "jss-plan": { alt: "Ground floor plan of JSS Private School from the tender set, scale 1:600.", caption: "Ground Floor Plan, 1:600" },
  "jss-entrance": { alt: "Render of the JSS Private School entrance with flags and a stone-clad wall." },
  "jss-sheet-sections": { alt: "Tender drawing: bay sections through Block B, the multipurpose hall and swimming pool, scale 1:50.", caption: "Bay Sections, Block B, 1:50" },
  "jss-sheet-elevations": { alt: "Tender drawing: elevations of the academic block and multipurpose hall with the exterior finishes schedule.", caption: "Elevations 1, 2, 3, 4" },
  "jss-field": { alt: "Render of the school's running track and sports field." },
  "jss-facade": { alt: "Render of the school's main facade and entrance canopy." },
  "villa-front": { alt: "Render of the luxury villa's front elevation at dusk." },
  "villa-entrance": { alt: "Render of the villa's arched entrance." },
  "villa-courtyard": { alt: "Render of the villa's covered courtyard lounge." },
  "villa-plan": { alt: "Ground floor plan of the villa." },
  "tower-render": { alt: "Render of the residential tower at dusk with its curving screen facade." },
  "tower-plan": { alt: "Podium plan of the residential building with the pool deck." },
  "tower-street": { alt: "Street-level render of the residential tower's entrance.", caption: "G + 2P + 17 Residential Building" },
};
