// Generated by scripts/build_images.py. Do not edit by hand.
export const images = {
  "cover-strip": {
    "w": 159,
    "h": 596,
    "widths": [
      159
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABwAwCdASoGABgAPu1kqU4ppaOiMAgBMB2JZwDMHA0v/7nIUAAAzfTBoOinS/hqiMMOu9eIHKamuqb7gBloAAAA"
  },
  "portrait": {
    "w": 246,
    "h": 258,
    "widths": [
      246
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwBACdASoXABgAPu1srVCppiQiqAqpMB2JaQAAIhgDGwnOhIldoQ7DejzVJqj0hmgA/uc7w+O/MwEDLEitEacXoaKGpHh80D7TBsp/cfZ/9O7rTgQH+3sYacmbwljXNcYA6/zAmwAAAA=="
  },
  "cg-sitemap": {
    "w": 1182,
    "h": 837,
    "widths": [
      480,
      800,
      1182
    ],
    "lqip": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAABwAwCdASoYABEAPu1qrVEppaQiqAqpMB2JaQAAOocFcCBGDAAA/vB+MPjEMXnyuFLwcAAA"
  },
  "cg-axo": {
    "w": 317,
    "h": 205,
    "widths": [
      317
    ],
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwBACdASoYABAAPu1yrU+pp6QiMAgBMB2JZwC3uB6WBwyVmn/0jzLXQwAA/vOB8u7UTgtEoIvIwXMESSiinQM7dXLyMVjsm3AYwA6t8ScAAA=="
  },
  "cg-plan-1": {
    "w": 373,
    "h": 527,
    "widths": [
      373
    ],
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAwCdASoRABgAPu1iqE2ppaOiMAgBMB2JZwDMWCHfiTeCewszgAD+77pQF674SBYqNxijYWrCHbpyvQLDomeEUTcXmCnQAAA="
  },
  "cg-plan-2": {
    "w": 373,
    "h": 527,
    "widths": [
      373
    ],
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAwCdASoRABgAPu1oq08ppiOiMBgIATAdiWkAz2QQ793xOos/UAD+8c9TF8bpI2soL48djxYFu1Mc5dbd7pJ1bRiWTZpUAAA="
  },
  "cg-section-hall": {
    "w": 842,
    "h": 381,
    "widths": [
      421,
      842
    ],
    "lqip": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAgCdASoYAAsAPu1iqU2ppaOiMAgBMB2JaQAAfj4AAP7wlS6zBqt00i9O4vrZ/gA="
  },
  "cg-detail-ground": {
    "w": 160,
    "h": 154,
    "widths": [
      160
    ],
    "lqip": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAgCdASoYABcAPu1wsFItJiSiqAgBoB2JaQAAPaaKAAD+8MB2WV+eYAAAAA=="
  },
  "cg-detail-sprung": {
    "w": 160,
    "h": 51,
    "widths": [
      160
    ],
    "lqip": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAADQAgCdASoYAAgAPu1iqU2ppaQjMAgBMB2JaQAAfqoAAP7wlCevNWAA"
  },
  "cg-section-library": {
    "w": 842,
    "h": 367,
    "widths": [
      421,
      842
    ],
    "lqip": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAgCdASoYAAoAPu1kqU2ppaOmMAgBMB2JaQAAetCIAAD+8JKbKAVDk8hAAA=="
  },
  "cg-detail-greenroof": {
    "w": 147,
    "h": 143,
    "widths": [
      147
    ],
    "lqip": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAgCdASoYABcAPu1sq1EppaOiqAqpMB2JaQAAOuHj4AD+8Hz/obS4PBw3du+TIgiWVSupeW5cAAAA"
  },
  "cg-detail-cltwall": {
    "w": 34,
    "h": 154,
    "widths": [
      34
    ],
    "lqip": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADwAgCdASoFABgAPu1iqU2ppaOiMAgBMB2JaQDMHC0kAAD+8I43xhMM0AA="
  },
  "cg-study-1": {
    "w": 195,
    "h": 146,
    "widths": [
      195
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwBQCdASoYABIAPuVepk2pJSOiN/VYASAciWcAACldPOxt6tgg3y9q64vXGOl/oiO+AAD+ycPWCV87reQPedhe1RnfLRcjkhfitlWgJtsq5B9jDlwBOOFcd22RUUFs1uWSuQAA"
  },
  "cg-staircase": {
    "w": 198,
    "h": 146,
    "widths": [
      198
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQBACdASoYABIAPulipE2pJaMiMAwBIB0JYwAAMM15ueW7NEarOJt2QADzFdOpuOGJgEeL5SBDAedz9XQNYflQnO9uqjFVfrZhloy6kZayMFM7rom0xMyeNUZAAA=="
  },
  "cg-study-2": {
    "w": 198,
    "h": 146,
    "widths": [
      198
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQBACdASoYABIAPu1gqE2ppaOiMAgBMB2JZQDG9CDZ4ytu7rmcvhVCop82AP0SuqNM5DfNFYK/Gr9XNI/yYQed1qLyOH0WfISid8AoZZRzEFFzV5qMXaGZygbMVMNRH2AAAA=="
  },
  "cg-plan-hall": {
    "w": 251,
    "h": 202,
    "widths": [
      251
    ],
    "lqip": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAwCdASoYABMAPu1usFIppiSjqAgBMB2JaQDQVBEcbe3vhesAlAAA/vHX0BB6jpN7xYAbQiTFogAAAAA="
  },
  "cg-plan-library": {
    "w": 256,
    "h": 168,
    "widths": [
      256
    ],
    "lqip": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAQAwCdASoYABAAPu1kqU4ppaOiMAgBMB2JaQAAetFfQEAA/vBnhepw5gIgJlJnsnYi/3OBAAA="
  },
  "cg-hall-1": {
    "w": 199,
    "h": 148,
    "widths": [
      199
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACQBACdASoYABIAPu1mqk2ppaQsMAgBgB2JZQC26L/DAeHuWGOcoe72OaUl7wAA/lhrT5tHrlEbT9UZGlGsXN59hrnuij4U7UwXD4hURpnGVz5LsKALDUh9PLe3HsKXJ2gyYAAA"
  },
  "cg-hall-2": {
    "w": 199,
    "h": 148,
    "widths": [
      199
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQBACdASoYABIAPu1qq08ppiOiMBgIATAdiWUArAAKBOaXbzPazICLAADKpfRj0rbL1ddFB90KyqwmrRuPBkhl0WFVZSRzZO+9Sg5jViRF7e1FcIP8gmlB8H00AA=="
  },
  "cg-hall-3": {
    "w": 199,
    "h": 148,
    "widths": [
      199
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQBACdASoYABIAPtFWoU2oJSMiN+gBABoJZQC+SCLs+eUH0IkUtiUSfirZTf0DsAD9ENDwaMOh0qpX7Qqi/Zq0iH01X7e5zgm0OotocdPifDeMB/QnTi47WtJ14VmzIeLoAA=="
  },
  "cg-yoga": {
    "w": 199,
    "h": 148,
    "widths": [
      199
    ],
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwBACdASoYABIAPulcp02pJSOiN/VYASAdCWMAqPQMVHLPwPTXPrbdaG/EAuE/zQAAzeK9CvIuWERbQdqdhMS161/B9wBNfJbge5CjzSrgQ36DEl1lBn4qrxyKFzQJULachddsETOcbAAA"
  },
  "cg-art": {
    "w": 199,
    "h": 148,
    "widths": [
      199
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQBACdASoYABIAPu1oqk4ppiQiMAgBMB2JZwC/OB5rj03+mMrXOLJCCh5wAMyP+Wiuq4CqmCQv7Sz+rPkoRQ/BruA6X9LR0dRRFSPbkyIJ7s/AsFltdDHrozV9wAAA"
  },
  "cg-aerial": {
    "w": 199,
    "h": 148,
    "widths": [
      199
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoYABIAPuFWpU2opKOiN/qoARAcCWcAvVgA4ZjDK4CrhSfgAPxiKibP5U/UsixE46GiPFyXcVUIumRbx/e/WqqAkDmMx8K3GaIIIwwYeps881fV9isAAAAA"
  },
  "cg-plan-11a": {
    "w": 269,
    "h": 223,
    "widths": [
      269
    ],
    "lqip": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAgCdASoYABQAPu1wsFKppiSiqAgBMB2JaQAAPfn8AAD+8GkrZZNpbT5gryps0+7bKIXWc+GpsAAA"
  },
  "cg-plan-11b": {
    "w": 273,
    "h": 101,
    "widths": [
      273
    ],
    "lqip": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAgCdASoYAAkAPu1iqU2ppaQiMAgBMB2JaQAAfqoAAP7waOqf70vfXVEMXmgA"
  },
  "cg-greenhouse": {
    "w": 200,
    "h": 149,
    "widths": [
      200
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQBACdASoYABIAPtFYok2oJaMiN+gBABoJZQDCgCfgG3uhP+EbTlqocZYAAPmtx2RzH6rqS1zCzNv59Kfg5fdrx10wz97/L3yOig2oI6y3EBShp/o3JICIbcaybBAA"
  },
  "cg-kitchen": {
    "w": 199,
    "h": 148,
    "widths": [
      199
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACQBACdASoYABIAPu1iq02ppaQiMBgMATAdiWUAnQAOFWPlWNbiyqt6yXUG2wAA/p3NHU5cka0vFmh1gLqRcZfpSBxvfYLOoTMnzgdDswLKXADziM7QpETv41iQ2rv0DRoGEI/F2EAAAA=="
  },
  "cg-cooking": {
    "w": 199,
    "h": 148,
    "widths": [
      199
    ],
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwBACdASoYABIAPu1kqU2ppaOiMAgBMB2JZQCvLW0CFv2uppU7SeOUGrhGBaR0dAAA/l/ONbA/TiefqYPqAD+sBDq/sByZrZDPmWTErh9kxc6tMVQD6IlQ07obO6kCEzUjePS7xNnVA7qtnAA="
  },
  "fc-photo": {
    "w": 336,
    "h": 527,
    "widths": [
      336
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAwCdASoPABgAPu1krU6ppaSiMAgBMB2JZwAAUquv7+rHfF2UMhZgAP7wKR7eUwQn/6ZRQehVcOlI/jBcF8k9AKnpuS4Qt6FVY+QUtzl09jgA"
  },
  "fc-model-1": {
    "w": 367,
    "h": 526,
    "widths": [
      367
    ],
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABwBACdASoRABgAPu1kqE2ppaOiMAgBMB2JZQAAYclKVz3Fi9IeKZFy3da04AD7jc/HZnGdYUxseZ7gQkAmGMu/18AlCFp5Q1No8m84NbukUKS77Yxee/vGeqUJAvTGAAA="
  },
  "fc-model-2": {
    "w": 382,
    "h": 248,
    "widths": [
      382
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAwCdASoYABAAPu1mq04ppaQiMAgBMB2JaQAASrB1z9DbkQ2EspU4AP7dTUfPJmlEkbWLw+MaOn86j0JqburH6ca1rI6LskNxb1AL+yTp6FAA"
  },
  "fc-model-3": {
    "w": 185,
    "h": 258,
    "widths": [
      185
    ],
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwBQCdASoRABgAPu1gqk2ppaQiMBgMATAdiWMAVidUYApUDLuwV9PZyhyw7SOyF2E6kAD+cTVFhF8zf1nm2zKO0QXQzRWbXW9aPGNc+73kvITwPgEBtl1Njmw5tondV5uWlfJrE3Bu2ytrC5AAAA=="
  },
  "fc-model-4": {
    "w": 182,
    "h": 258,
    "widths": [
      182
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACwBACdASoRABgAPu1srlCppiQiqAqpMB2JZQDCgA9juO+N1Ec4xEs04x+o7+0AAP5Ue+AIsN3K30OyryPn6dh0de/hHH2U1KUiW3cQjdyoyqSUqnUDrpfZ53L72vOqbR7aBNAA"
  },
  "fc-detail-parapet": {
    "w": 242,
    "h": 175,
    "widths": [
      242
    ],
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAwCdASoYABEAPu1orE+ppaQiMBgIATAdiWkAAC3B/d7GxCrZFHaAAP65KGhG/oKBkYLq0UC295jwXl1+klwkfzTY7AgA"
  },
  "fc-detail-floor": {
    "w": 242,
    "h": 138,
    "widths": [
      242
    ],
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAwCdASoYAA4APu1orU2ppqSiMAgBMB2JaQAAXE7UqSey1Y8y3FQAAP6pksC6Gjg72NMqHw/39x4uvtBQAA=="
  },
  "fc-detail-foundation": {
    "w": 242,
    "h": 210,
    "widths": [
      242
    ],
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwBACdASoYABUAPu1uqk8ppyOiMBgIATAdiWkAAC3OUJy2+kqxyOOGZar5iAD+uWibhswiAevIPdc3yCVWqGuFiDuRatackAAAAA=="
  },
  "fc-corten": {
    "w": 453,
    "h": 760,
    "widths": [
      453
    ],
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoOABgAPu1kqU2ppaQiMAgBMB2JQBOgBDmE6uIRzUgnyEAAAP7I47NyqXSlKcUWnTo57h9jscENYObvn19JYgNoKPl/vggRfda4y/n6A967XZJXrkXEnrGQhCokBVyWAAA="
  },
  "fc-exploded": {
    "w": 773,
    "h": 466,
    "widths": [
      386,
      773
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoYAA4APu1yrU+pp6QiMAgBMB2JaQAASlU0j86ix/iCAAD+tsALqrRZ1mTOu3az6jRhaM6ineg7Sn6jcOtp/dA3mPRYD6LHqhf62AAA"
  },
  "vt-castle": {
    "w": 401,
    "h": 340,
    "widths": [
      401
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwBACdASoYABQAPuVgpk2pJaOiN/VYASAciWUAzcAQ78NCL2/9X8iJSF6pNe96QuAA/nCx5Xmf5e+9EMJyoFv16j2UrCUGRGlrZW4Dp5OEQ+kAAAA="
  },
  "vt-auditorium": {
    "w": 842,
    "h": 596,
    "widths": [
      421,
      842
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQBACdASoYABEAPu1srVEppaQiqAqpMB2JZQC06A3qyjX7bGISX7mHAADdiQU0O0wNuW+bNvVUxGbBShYqsh0DZuOBUbh1Kxx+yKPh1yoy0I3zgTSEwAAA"
  },
  "vt-map-location": {
    "w": 1013,
    "h": 804,
    "widths": [
      480,
      800,
      1013
    ],
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQBACdASoYABMAPu1iqE2ppaOiMAgBMB2JaQAAW626gk7cNmYevzJmkAD+6nkg6THm7dGCQrIU9X7rFPp7IXeaDHu+m2KAAAA="
  },
  "vt-map-context": {
    "w": 945,
    "h": 779,
    "widths": [
      480,
      800,
      945
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwBACdASoYABQAPu1kqk2ppaQiMAgBMB2JaQAAW/BISYSrnGtNY2PQcAAA/vN9tMrAFXwRhuHdIN2nqOFcYh7fB5eUJweR82G1gGgAAAA="
  },
  "vt-map-movement": {
    "w": 937,
    "h": 684,
    "widths": [
      480,
      800,
      937
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwBACdASoYABIAPuFUpU2opCOiN/qoARAcCWkAAFu1D53V8OkKinV/beAA/vTTNGGb1AfdkS4SWds/FWYp1+9l/PlWHQ+JXOvNm/BPQAA="
  },
  "vt-map-climate": {
    "w": 1090,
    "h": 710,
    "widths": [
      480,
      800,
      1090
    ],
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAwCdASoYABAAPu1yrU+pp6QiMAgBMB2JaQAAW+/77VekszzrB3kAAP7zfcWYckxUy2GyAPFJBAmpZ4uyVn2PNvAAAA=="
  },
  "vt-massing-1": {
    "w": 128,
    "h": 90,
    "widths": [
      128
    ],
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAwCdASoYABEAPu1kqU2ppaQiMAgBMB2JaQAAW+n8zt74beOhwAD+7dvuHb6Ou51MJg/LhC06MVrIy/ruNixGb06AAA=="
  },
  "vt-massing-2": {
    "w": 144,
    "h": 95,
    "widths": [
      144
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAwCdASoYABAALrV2u12jqampiYC0S0gABizE0h+vPYv3XlhgsAD+9z1aWeqnhE6ZIqX12k/mDtmYxbd9+UwA"
  },
  "vt-massing-3": {
    "w": 137,
    "h": 96,
    "widths": [
      137
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQBACdASoYABEAPu1mpk2ppaMiMBgMATAdiWcAzYQQ4Yoqpp0eK85Z9G4Plw/TcAD+8D6U6xEC2hGqXzyd/jNRxtIxwq5LIeY9QOuxmYHJmYMrgAA="
  },
  "vt-massing-4": {
    "w": 132,
    "h": 95,
    "widths": [
      132
    ],
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABQBACdASoYABEAPu1kqU2ppaQiMAgBMB2JZwDPoCIfxrJlLD903LMzAmQAAP7yKMEBgsRLmwOxj6vpi6Dm/7illHB2sK3QAAA="
  },
  "vt-massing-5": {
    "w": 132,
    "h": 97,
    "widths": [
      132
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQBACdASoYABIAPu1gqE2ppSOiMAgBMB2JZwAAV//VunVIIlBMoRGtWOINYM64AAD+8ioG0B1CyOfiArrJLXfhb/jsS0sFkwEpwhNNbofuAAAA"
  },
  "vt-sketch": {
    "w": 580,
    "h": 322,
    "widths": [
      290,
      580
    ],
    "lqip": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAgCdASoYAA0APu1kqU2ppaQiMAgBMB2JZwAAetDDQAD+8E9RzHGNAeMVFXKTTpbMJdbACAA="
  },
  "vt-form-1": {
    "w": 141,
    "h": 105,
    "widths": [
      141
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAwBACdASoYABIAPu1cqE2ppKOiN/VYATAdiWkAAC30/pFr83CP2vqAmZAA/vN0Apkm8zSeb/bgyJldCk9QAAAA"
  },
  "vt-form-2": {
    "w": 140,
    "h": 106,
    "widths": [
      140
    ],
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAABQBACdASoYABIAPu1gq02ppSQiMBgMATAdiWkAAC5OXhPEQ87w63T+slLAAP7zfbU3bu83Nm2yBsgdCPy6rh73SjAAAAAA"
  },
  "vt-form-3": {
    "w": 136,
    "h": 126,
    "widths": [
      136
    ],
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAwCdASoYABYAPu1qrVEppaQiqAqpMB2JaQAAPgBh4uctqkYRAAD+8GQVVeVW9AAqODiCO5bRRSd/9GXfDS3gAAA="
  },
  "vt-section": {
    "w": 730,
    "h": 560,
    "widths": [
      365,
      730
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAwCdASoYABIAPu1iqE2ppaOiMAgBMB2JZwAAW+swAo/nHIQeAAD+8fQa44gLDj1UMdeFI8U1xN1U4HLoAAAA"
  },
  "vt-exploded": {
    "w": 522,
    "h": 529,
    "widths": [
      522
    ],
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAwCdASoYABgAPuVepk2pJSOiN/VYASAciWUAACU5eHXcXd4KV2AAAP7zgri0DfBKy8IKvtejwCK+9NpGyiHWp8DEpA6zNAj/qMl33oAAAA=="
  },
  "vt-foyer-1": {
    "w": 254,
    "h": 249,
    "widths": [
      254
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQBACdASoYABgAPu1qrU+ppiQiMBgIATAdiWdf9lu9By490aSzpyifUUmm1APyAADxjr1PLWE95oEIaN3dKZ++V0KZMGUqOB4cGkHcmsUOLlhWlJ5c/MDXk8b/AAAA"
  },
  "vt-foyer-2": {
    "w": 254,
    "h": 249,
    "widths": [
      254
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABwBACdASoYABgAPu1gpk4ppSMiMBgMATAdiWcAxNhX4LQkoxEbTKCVfmYZTAD8RYTCIntcrWagr6EXcG3P4BiX03Gfx6df3q5mbShB5c3kWGa/kuAAAA=="
  },
  "ea-siteplan": {
    "w": 402,
    "h": 311,
    "widths": [
      402
    ],
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQBACdASoYABMAPuVgpk2pJaOiMAwBIByJZQDJECHfvvMZ+m5rLpwpIVW+K2AA/sLlJ3fUVhEzri8CR1edC3zYMxa/D22QsAA="
  },
  "ea-courtyard": {
    "w": 842,
    "h": 596,
    "widths": [
      421,
      842
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACQBACdASoYABEAPu1qqU+ppiOiKA1RMB2JYwC7M47BeO7EZunb5uyag2Mrg4gA4k/B0dz1OHfkrcGrypa0WKm/TwvJQHxzl/6mxMyyPB3XbcLx0vZ9hpALOVCpv88oB92xC6TnLAAAAA=="
  },
  "ea-plan-site": {
    "w": 542,
    "h": 1036,
    "widths": [
      480,
      542
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAwCdASoNABgAPu1yrU+pp6QiMAgBMB2JZQAAUrae751mzzXtocAA/sg6AQFb8QnWvI4xuVb2yNB+url1QtAA"
  },
  "ea-plan-a": {
    "w": 271,
    "h": 495,
    "widths": [
      271
    ],
    "lqip": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAwCdASoNABgAPu1kqU4ppaOiMAgBMB2JZwAAW+yvwtHRktamAAD+833vmuW6bRLG33jEwjgAAA=="
  },
  "ea-plan-b": {
    "w": 267,
    "h": 481,
    "widths": [
      267
    ],
    "lqip": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAwCdASoNABgAPu1kq04ppaQiMAgBMB2JZwAAW+oU2e0f7Bpcj6gAAP7zftsGCxTd8CnA9SKAAA=="
  },
  "ea-landscape": {
    "w": 741,
    "h": 519,
    "widths": [
      370,
      741
    ],
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQBACdASoYABEAPuFcp02opSOiMAwBEBwJZQAAW+oLO+AdafmkkHvPYAD+7VlZBxd/QFrepPE/yD7aNgezWXBBHz+b6VYh+ms61kXN/8AAAA=="
  },
  "ea-model-1": {
    "w": 297,
    "h": 596,
    "widths": [
      297
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAwCdASoMABgAPu1oqk6ppiQiMAgBMB2JQBWAA1ngHUq9k+gZgAD95uw2yVLyj7q7EroZDr5/IDdJ5z5NG6wCTPEOYB1YhQTbdwAAAAA="
  },
  "ea-model-2": {
    "w": 344,
    "h": 511,
    "widths": [
      344
    ],
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAwCdASoQABgAPu1mq04ppaQiMAgBMB2JYwCdACG6UItEEcvvzA1wAP7t4AGia0LG2oMpPOtIUdN0E9k+lS7GKzMHkXFwfzPiIaciCMVuQTkv6QsKhYhPrYTHKOK19PEmO5gEiy1RS9gA"
  },
  "ea-model-3": {
    "w": 144,
    "h": 191,
    "widths": [
      144
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQBACdASoSABgAPu1gqU2ppSQiMBgMATAdiWUAxnwJvv677BTeLitOtqsAAPp62k3xqRYB+y9D85gf6ueRdCztEHSeLUQazVVesbrcOvOw4XgOH6Fp9laM/newAA=="
  },
  "ea-model-4": {
    "w": 144,
    "h": 191,
    "widths": [
      144
    ],
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwBACdASoSABgAPuVgpk2pJaOiN/VYASAciWUAuwAPY3uI2Pamiqc/LfUDnb7Hd4AAyxQ/rfl/iL1vT7/8lQckn6fYjTnOLI4PESCnK48E5j6BdQTGkxo3D5hyRQA7eqWO0xOegCa1yYAAAAA="
  },
  "ea-sketch": {
    "w": 144,
    "h": 121,
    "widths": [
      144
    ],
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAwAwCdASoYABQAPu1qrVEppaQiqAqpMB2JaWi2ABwH+QAAAP7wZDrTAOW5iWLu/sR57dKHPl6laMI8CKLpAO4kBUoAAA=="
  },
  "ea-elevation-1": {
    "w": 469,
    "h": 163,
    "widths": [
      469
    ],
    "lqip": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAQAwCdASoYAAgALrV2u12jqampiYC0SzgABc3LtxuEIUAA/vfpfWMmwHDtBfBUrFwejDQAAAA="
  },
  "ea-elevation-2": {
    "w": 469,
    "h": 183,
    "widths": [
      469
    ],
    "lqip": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAwAwCdASoYAAkALrV2u12jqampiYC0S0gABc8FGBaWtlYAAP74uYoldCUnWl83nR8/AKAAAAA="
  },
  "ea-wallsection": {
    "w": 319,
    "h": 588,
    "widths": [
      319
    ],
    "lqip": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAwCdASoNABgALrV2u12jqampiYC0SzgABc3UQLNnAyAnx0OAAP7zgEkNq8BUyy6ticCngpVdNyAgAAA="
  },
  "ea-detail-base": {
    "w": 114,
    "h": 119,
    "widths": [
      114
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQBACdASoXABgAPuVepU2pJSOiMAwBIByJQBfnBH3H0yGiefxnpLz1XjMAAP7gyPchJ1SBeZa34cocOBEtiPoYOxdAbZS/9t2kYndB7y1RiKcUW0zdqTWeYV2jYYAA"
  },
  "ea-detail-floor": {
    "w": 99,
    "h": 126,
    "widths": [
      99
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQBACdASoTABgAPuFeqU2opSQiMAwBEBwJZQAAW+s/7saqf1siXx1q9QmAAP7gyN4obdGgZocB3r59waifSy9LqTVofa8mi3fJOVX0TN5JNXzEbU4/EVAA"
  },
  "ea-balconies": {
    "w": 842,
    "h": 596,
    "widths": [
      421,
      842
    ],
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoYABEAPu1eq02ppKQiMBgMATAdiWMAsR7fAZfD04OnAjB64ADKCOuGu/wDCwI1Kq3SjV8zE27lYv+XWCWcW6xnlj32sFQG4XdIVuUYwH6Do+zlb1+xUsPzAocxXQKDuA3lwnmIU71Vx0AA"
  },
  "ea-facade": {
    "w": 279,
    "h": 596,
    "widths": [
      279
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoLABgAPu1iqU2ppaOiMAgBMB2JQBOmUABplpOClyzQWgAA/mMR5cbSp2qj/xuhB79XGmwOk3eAIyfdpRze4RsMKFViamgKut/BIQAA"
  },
  "ea-bedroom": {
    "w": 231,
    "h": 246,
    "widths": [
      231
    ],
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABwBQCdASoXABgAPu1erU2ppKSiMBgMATAdiUAXZmMAI/Qr53YKh+xq+jbfR+vKqLlu5cMgAP0cEU4wQljzERMtFA0+WOmzJ90a9FuQRaRemVMpcfzf6Ag+Dx3TdD4U2p14Tqp2WB++j+9rHr5JYqZ7DowxfOgU1hIuYAMAgAA="
  },
  "ea-farm": {
    "w": 231,
    "h": 246,
    "widths": [
      231
    ],
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACwBACdASoXABgAPu1gq1AppSOisBgIATAdiUAABRwiagnmUN4rMDJzXegne0DuAP6exCwt5sVTKQlA0AJU7R0FMgmb+hqP2E887AuLLYgyxSbwGcrHGft5ZmxWy2hFxlhTXFDmxVYnRsucNVfSsPFSttULjFxkP7Lqx95rQUTKgFGAAAA="
  },
  "ea-concept": {
    "w": 474,
    "h": 663,
    "widths": [
      474
    ],
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAwCdASoRABgAPu1gq1AppSOisBgIATAdiWliSQAbpYtnh6WO9vxgAP7wLvknOnaiexah+BNsY9D1Ymny7ZPAa0hvVaYVyOXSPEjswCAAAA=="
  },
  "ea-study-cafe": {
    "w": 77,
    "h": 84,
    "widths": [
      77
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAwCdASoWABgAPu1krE+ppSQiMBgIATAdiWlo2QAbpYj/IStsVigA/vAxAoXngL5sRfcfYeYXRNcb2R+9Q9JFkkRrDV30gNDGUQEhAAA="
  },
  "ea-study-office": {
    "w": 91,
    "h": 52,
    "widths": [
      91
    ],
    "lqip": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAwCdASoYAA4APu1krU6ppaSiMAgBMB2JaQAAYf+Eo6sNxm880oAA/u16vwDbB/c/Oeo0wYS+qlgAAAA="
  },
  "ea-study-shared": {
    "w": 87,
    "h": 77,
    "widths": [
      87
    ],
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAwCdASoYABUAPu1oqk+ppiOiKA1RMB2JaQAALngW2oXcrSr6AAD+833yrDkT3L71A/v7n5z//EVea8+MJdFaAAA="
  },
  "ea-study-private": {
    "w": 86,
    "h": 59,
    "widths": [
      86
    ],
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAwCdASoYABAAPu1kq04ppaQiMAgBMB2JaQAAXKIB03C5xRwbAAD+835iFOpoxbc5178Mkm/WHITvReAAAA=="
  },
  "ea-study-glass": {
    "w": 79,
    "h": 58,
    "widths": [
      79
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwBACdASoYABIAPu1qq08ppiOiMBgIATAdiWcAACof632zKYp+MIkvcx4GjDcRygAA/vHgwg+ziVfE5A1RteK9cOs69f6jZ8cY9K7tkr9hwAAA"
  },
  "ea-study-curved": {
    "w": 81,
    "h": 62,
    "widths": [
      81
    ],
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACQAwCdASoYABIAPu1wsFIppiSiqAgBMB2JaQAALtHsO1gCJtYAAP7x0KbSgaKih0CyYTEluO+hdo99/N4HtH0p5ozTWsXYyKDwAAAA"
  },
  "dc-logo": {
    "w": 255,
    "h": 131,
    "widths": [
      255
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAwCdASoYAAwAPu1kqU2ppaQiMAgBMB2JZQCsACHSwkuuPlRIAP7h4NNnZOhrPi1l9s+PbzC439tfOIKk/2YLDkKpyKde8VCap2cTQAA="
  },
  "jss-logo": {
    "w": 72,
    "h": 77,
    "widths": [
      72
    ],
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwBACdASoWABgAPu1ur1KppiQiqAgBMB2JQBadAe0GD2v74DFmmUyCoUk8OsHMAP7yKW9X4qyYaRv4ff5zxvTnL2He5w0GcQNrDr25BT2S1DdmWQu7a84ShIJBHWxoNcvJg7wqYcWu75KuqbmGRlkfXQAAAA=="
  },
  "jss-plan": {
    "w": 3309,
    "h": 1539,
    "widths": [
      480,
      800,
      1200,
      1800,
      2600,
      3309
    ],
    "lqip": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAABQAwCdASoYAAsAPu1kqU4ppaOiMAgBMB2JaQAAetHewFdaAAD+8ID9acSwJqcbQAAAAA=="
  },
  "jss-entrance": {
    "w": 395,
    "h": 224,
    "widths": [
      395
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQBACdASoYAA4APu1krU2ppaSiMAgBMB2JZQC/OB6vpEjNG5v3O+zRhxaQAP7GtxeNNXzQDS7KkSmCvhTZ0eLb8ZMs2Uvger4Tt9pjRKvdf77ecFIKUELdPA2KpV1po2gAAA=="
  },
  "jss-sheet-sections": {
    "w": 2767,
    "h": 2251,
    "widths": [
      480,
      800,
      1200,
      1800,
      2600,
      2767
    ],
    "lqip": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABwAwCdASoYABQAPu1cq04ppKQiMBgMATAdiWkAADpwJ3UbTAgA/vBkOtRzep2OcfeN4vh3NT5SzpgAAAA="
  },
  "jss-sheet-elevations": {
    "w": 2776,
    "h": 2251,
    "widths": [
      480,
      800,
      1200,
      1800,
      2600,
      2776
    ],
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAwCdASoYABMAPu1uq1EppiOnKAqpMB2JaQAALnWbahbran1NAAD+8CgVJG46T3u1f47UTzpzzWpD5AAAAA=="
  },
  "jss-field": {
    "w": 384,
    "h": 218,
    "widths": [
      384
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoYAA4ALrV2u12jqampiYC0SgCdH8AExkHnDAV3gCQKAAD9zvsAK4gCWNkR/xl9JB9Kt/aphhh5EosFSx1LN6hxPjm+4+WqOFatWgAA"
  },
  "jss-facade": {
    "w": 385,
    "h": 218,
    "widths": [
      385
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwBACdASoYAA4APu1mqk2ppaQiMAgBMB2JYwC7AGjrPSIq+pWXOSdO/SAA/rPO0522fpuPI5OowCy5SpiDGXqYHb7xRDVrWTL95udtPLYEw1Yj1mAAAA=="
  },
  "villa-front": {
    "w": 372,
    "h": 217,
    "widths": [
      372
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQBACdASoYAA4APu1qrU8ppiQiMAgBMB2JQBWABEPvSdbZM8x2cauEAAD+1H5WoRqDo72E4HN2FUldREljHhcASdeogPbieJm8v6bq9l5vCuR67qYSSIAA"
  },
  "villa-entrance": {
    "w": 372,
    "h": 217,
    "widths": [
      372
    ],
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAwCdASoYAA4APu1kqk2ppaQiMAgBMB2JYwCdAB5aZpI92B9uBgD8gqHn+/HlTKin0H3IPGuHcPw3FjyCLoDnr5GHh20wjC3wQdn+TU6h8JJAirfC8JMAAAA="
  },
  "villa-courtyard": {
    "w": 372,
    "h": 217,
    "widths": [
      372
    ],
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACQAwCdASoYAA4APu1kqk2ppaQiMAgBMB2JQBOgA2DMEJ+cWgHwAPih0BR93i4lELnHnigZM5O5SQm13jbiD8IVYSXIoKqLzB+PDc06akcePw9w1cr+w31ggAA="
  },
  "villa-plan": {
    "w": 354,
    "h": 229,
    "widths": [
      354
    ],
    "lqip": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAAAwAwCdASoYABAAPu1iqU2ppaQiMAgBMB2JaQAAetCxIzgAAP7wY41zUo2zVXnQgAA="
  },
  "tower-render": {
    "w": 363,
    "h": 470,
    "widths": [
      363
    ],
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABwBQCdASoTABgAPulkqU2pJaQiMBgMASAdCUAWnQIHRzmqGH/u1MOcKTkqFf2sbUMjUK5AAP7D1zKLRBBo1QBql4xS1cjVvSXxxhMDMZ3zm2TOSweM4aRNJp5mg9dGmBXSktJR/8X7NkWKhSj0pSSkPJOhu1AA"
  },
  "tower-plan": {
    "w": 336,
    "h": 259,
    "widths": [
      336
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACQBACdASoYABMAPuFWpk2opKOyN/qoAkAcCWcAAFxj/KpYL2trif0uxp7WjgAA/vOTI/rY9mn1cm0+LkMwREyNI7V9NcLSTPWoJFU88wFWgAAA"
  },
  "tower-street": {
    "w": 374,
    "h": 211,
    "widths": [
      374
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JYwCdMoRwABqyJZFuwZ5sAPj5dbzZJF15dkQnlv6YMY5+GdVpvPkPO0gCxhN/r6mgH6h+49STTKT1Yb5VyAAA"
  }
} as const;

export type ImageId = keyof typeof images;
