"""Encode figure masters into responsive AVIF + WebP files and a typed manifest.

usage: py -3 scripts/build_images.py assets-src/figures public/img src/content/images.ts

Masters at screen resolution (about 72 dpi) ship at their native width and a
half-width copy; high-resolution masters (vector renders) ship a width ladder.
"""
import base64
import io
import json
import sys
from pathlib import Path

from PIL import Image, ImageFilter

LADDER = [480, 800, 1200, 1800, 2600, 3400]
QUALITY = {
    "photo": dict(avif=60, webp=82),
    "drawing": dict(avif=74, webp=90),
}


def widths_for(w, dpi):
    if dpi >= 144:
        return sorted({x for x in LADDER if x < w} | {w})
    return sorted({w} | ({round(w / 2)} if w >= 560 else set()))


def lqip(im):
    small = im.copy()
    small.thumbnail((24, 24))
    small = small.filter(ImageFilter.GaussianBlur(1))
    buf = io.BytesIO()
    small.save(buf, "WEBP", quality=40)
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode()


def main():
    src, out, ts = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
    out.mkdir(parents=True, exist_ok=True)
    manifest = json.loads((src / "manifest.json").read_text())
    entries = {}
    total = 0
    for fid, meta in manifest.items():
        im = Image.open(src / f"{fid}.png").convert("RGB")
        q = QUALITY[meta["kind"]]
        ws = widths_for(im.width, meta["dpi"])
        for w in ws:
            frame = im if w == im.width else im.resize((w, round(im.height * w / im.width)), Image.LANCZOS)
            a = out / f"{fid}-{w}.avif"
            b = out / f"{fid}-{w}.webp"
            frame.save(a, "AVIF", quality=q["avif"], speed=6)
            frame.save(b, "WEBP", quality=q["webp"], method=6)
            total += a.stat().st_size + b.stat().st_size
        entries[fid] = dict(w=im.width, h=im.height, widths=ws, lqip=lqip(im))
        print(f"{fid:24s} {im.width}x{im.height} -> {ws}")
    body = json.dumps(entries, indent=2)
    ts.write_text(
        "// Generated by scripts/build_images.py. Do not edit by hand.\n"
        "export const images = " + body + " as const;\n\n"
        "export type ImageId = keyof typeof images;\n",
        encoding="utf-8",
    )
    print(f"{len(entries)} figures, {total / 1e6:.1f} MB encoded")


if __name__ == "__main__":
    main()
